filebeat.inputs:
# 读取 raw_data 日志文件
- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/source/raw_data*.log"
  
  # 多行日志处理 - 合并被分割的 JSON 数据
  multiline.pattern: '^\[20\d{2}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\]'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 1000
  
  # 添加字段标识来源
  fields:
    log_type: "raw_data"
    service: "iot_gateway"
  fields_under_root: true

# 可选: Docker 容器日志
- type: container
  enabled: false
  paths:
    - '/var/lib/docker/containers/*/*.log'
  
  processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

# 可选: 监控系统日志
- type: log
  enabled: false
  paths:
    - /var/log/*.log
    - /var/log/messages
    - /var/log/syslog

# 处理器
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# 输出到 Logstash
output.logstash:
  hosts: ["logstash:5044"]

# 可选: 直接输出到 Elasticsearch (注释掉上面的 Logstash 输出)
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "filebeat-%{+yyyy.MM.dd}"

# 日志级别
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# 禁用 SSL 验证
ssl.verification_mode: none

# 监控配置
monitoring.enabled: false
