filebeat.inputs:
# 读取 raw_data 日志文件
- type: log
  enabled: true
  paths:
    - "/usr/share/filebeat/source/*.log"
  
  # 多行处理：不是{开头的行都合并到上一行
  multiline.pattern: '^\{'
  multiline.negate: false
  multiline.match: after
  multiline.max_lines: 2
  
  # 添加字段标识来源
  fields:
    log_type: "raw_data"
    service: "iot_gateway"
  fields_under_root: true
  
  # 优化文件读取
  scan_frequency: 5s
  harvester_buffer_size: 32768
  max_bytes: 20971520
  ignore_older: 0
  close_inactive: 5m
  
  # 不排除任何行，让Logstash处理
  # exclude_lines: ['^$', '^\s*$']

# 处理器
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# 输出到 Logstash
output.logstash:
  hosts: ["logstash:5044"]

# 可选: 直接输出到 Elasticsearch (注释掉上面的 Logstash 输出)
# output.elasticsearch:
#   hosts: ["elasticsearch:9200"]
#   index: "filebeat-%{+yyyy.MM.dd}"

# 日志级别
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# 禁用 SSL 验证
ssl.verification_mode: none

# 监控配置
monitoring.enabled: false
