http.host: "0.0.0.0"
path.config: /usr/share/logstash/pipeline
path.data: /usr/share/logstash/data
pipeline.workers: 2
pipeline.batch.size: 125
pipeline.batch.delay: 50

# X-Pack monitoring
xpack.monitoring.enabled: false

# API settings
api.http.host: "0.0.0.0"
api.http.port: 9600

# Log level
log.level: info
path.logs: /var/log/logstash

# Enable automatic config reload
pipeline.reload.automatic: true
pipeline.reload.interval: 3s
config.reload.automatic: true
config.reload.interval: 3s
