server.name: kibana
server.host: "0.0.0.0"
server.port: 5601

# Elasticsearch configuration
elasticsearch.hosts: ["http://elasticsearch:9200"]

# Disable security features
xpack.security.enabled: false
xpack.encryptedSavedObjects.encryptionKey: "something_at_least_32_characters_long"

# Monitoring
monitoring.ui.container.elasticsearch.enabled: true

# Logging
logging.appenders:
  file:
    type: file
    fileName: /var/log/kibana.log
    layout:
      type: pattern
      pattern: "[%date] [%level] [%logger] %message"
  console:
    type: console
    layout:
      type: pattern
      pattern: "[%date] [%level] [%logger] %message"

logging.loggers:
  - name: http.server.response
    level: debug

logging.root:
  appenders:
    - console
    - file
